-- --------------------------------------------------------
-- Anfitrião:                    127.0.0.1
-- Versão do servidor:           8.4.3 - MySQL Community Server - GPL
-- SO do servidor:               Win64
-- HeidiSQL Versão:              12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- A despejar estrutura da base de dados para therecipe
CREATE DATABASE IF NOT EXISTS `therecipe` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `therecipe`;

-- A despejar estrutura para tabela therecipe.comentario
CREATE TABLE IF NOT EXISTS `comentario` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_utilizador` int NOT NULL,
  `id_receita` int NOT NULL,
  `comentario` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- A despejar dados para tabela therecipe.comentario: ~1 rows (aproximadamente)
INSERT INTO `comentario` (`id`, `id_utilizador`, `id_receita`, `comentario`) VALUES
	(1, 1, 2, 'Adorei esta receita');

-- A despejar estrutura para tabela therecipe.favoritos
CREATE TABLE IF NOT EXISTS `favoritos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_receita` int NOT NULL,
  `id_utilizador` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- A despejar dados para tabela therecipe.favoritos: ~3 rows (aproximadamente)
INSERT INTO `favoritos` (`id`, `id_receita`, `id_utilizador`) VALUES
	(25, 8, 1),
	(26, 2, 1),
	(27, 4, 1);

-- A despejar estrutura para tabela therecipe.receitas
CREATE TABLE IF NOT EXISTS `receitas` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `tempo` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ingredientes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `preparacao` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `imagem` varchar(128) DEFAULT NULL,
  `categoria` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `quantidade` int DEFAULT NULL,
  `orcamento` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- A despejar dados para tabela therecipe.receitas: ~41 rows (aproximadamente)
INSERT INTO `receitas` (`id`, `nome`, `tempo`, `ingredientes`, `preparacao`, `imagem`, `categoria`, `descricao`, `quantidade`, `orcamento`) VALUES
	(1, 'Caldo Verde', '35 min', '4 batatas em pedaços\n1 cebola\n2 dentes de alho\n2 c. sopa de azeite\n250 g caldo verde\n1/2 chouriço em pedaços, mais em rodelas para decorar\n1 c. café sal', 'Coza as batatas, a cebola e dois dentes de alho na água.\nQuando estiver cozido, triture tudo e leve novamente ao lume.\nJunte o caldo verde e os pedaços de chouriço e deixe cozer durante 10 minutos.\nRetire a sopa do lume e termine colocando um fio de azeite e umas rodelas de chouriço.', 'caldo_verde.jpg', 'Sopa', 'Sopa tradicional portuguesa, reconfortante e cremosa.', 4, 'Económico'),
	(2, 'Bacalhau à Brás', '45 min', '4 ovos\n3 gemas\n1 c. café sal\nPimenta q.b.\n4 c. sopa azeite\n1 cebola em meias luas\n1 folha de louro\n3 dentes de alho picados\n350 g de bacalhau desfiado\n125 g batata palha frita\nSalsa picada q.b.\nAzeitonas pretas q.b.', 'Coloque azeite numa frigideira alta, a aquecer, junte a cebola e o louro e deixe refogar.\nJunte os dentes de alho à frigideira e mexa. Junte o bacalhau já desfiado, calque e misture bem com a cebola.\nJunte cerca de 75g batatas palha frita e misture.\nParta os ovos para dentro de uma taça, tempere de sal e pimenta e bata bem.\nRetire o louro da frigideira, junte os ovos e misture bem (se estiver muito líquido, pode levar ao lume um pouco). Adicione a restante batata palha e envolva bem.\nJunte a salsa picada e as azeitonas antes de servir.', 'bacalhau_bras.jpg', 'Peixe', 'Clássico prato de bacalhau com ovos cremosos e batata palha crocante.', 4, 'Médio'),
	(3, 'Sopa de Peixe', '30 min', '1 c. chá de óleo de coco\n1 cebola média\n2 dentes de alho\n390 g de tomate em pedaços\n1 couve-coração pequena\n1000 ml de água (ou caldo de legumes)\n2 c. café de caril em pó\nFlor de sal q.b.\n3 lombos de pescada\n4 ovos escalfados\nSalsa picada q.b.', 'Deite o óleo de coco numa panela funda e adicione a cebola picada e o tomate pelado. Deixe cozinhar com a tampa até o tomate ficar macio.\nAdicione a couve-coração cortada em juliana e cubra com água (ou caldo de peixe se preferir) previamente aquecida e tempere com o caril e flor de sal. Deixe cozinhar por 15 minutos em lume brando.\nTriture o caldo com os legumes até obter uma consistência cremosa e adicione a pescada em pedaços pequenos.\nDeixe cozinhar até o peixe ficar tenro. Sirva cada dose com 1 ovo escalfado e salsa picada por cima.', 'sopa_peixe.jpg', 'Sopa', 'Sopa rica e saborosa com peixe fresco.', 4, 'Médio'),
	(4, 'Arroz de Marisco', '50 min', '500 g de preparado de arroz de marisco\n250 g de camarão de Madagáscar\n250 g de arroz carolino\n1 tomate médio\n1 ½ cebola roxa\n3 dentes de alho\n3 folhas de louro\n120 ml de vinho branco\n2 c. sopa de polpa de tomate\n1,5 l de água\n1 malageta\nSal q.b.\nPimenta q.b.\nCoentros frescos q.b.', 'Para preparar o caldo, coloque cerca de 1,5 litros de água, tempere com sal, uma folha de louro, uma malagueta e pimenta a gosto. Quando começar a ferver, junte o camarão e deixe cozer durante cerca de 5 minutos.\nAssim que os camarões estiverem cozidos, retire da água e passe por água fria de modo a parar a cozedura. Reserve o caldo.\nNum tacho com um fio de azeite, refogue a cebola roxa picada e os dentes de alho laminados. Deixe cozinhar até a cebola ficar translúcida.\nJunte o pimento cortado, o tomate em cubos e as folhas de louro. Deixe cozinhar por mais uns minutos.\nAdicione o vinho branco e deixe reduzir.\nJunte a polpa de tomate, mexa bem e adicione o arroz. Deixe fritar por alguns segundos, mexendo sempre.\nAdicione 500 ml do caldo de camarão e tempere com sal e pimenta. Deixe ferver mexendo de vez em quando.\nNos últimos 5 minutos de cozedura do arroz, adicione o preparado de marisco e os camarões. Retifique os temperos.\nEmprate e decore com coentros.', 'arroz_marisco.jpg', 'Peixe', 'Arroz rico e saboroso com mariscos frescos.', 4, 'Alto'),
	(5, 'Salada de Grão com Atum', '15 min', '1 cebola roxa\n1 tomate coração de boi\n1/2 dúzia de tomate cereja\n1 lata de atum em posta ao natural (85g)\n1 lata de grão de bico (260g)\nSumo de 2 limas\n60 ml de azeite\nSal q.b.\nPimenta q.b.\n3 ovos cozidos\nFlores comestíveis, opcional', 'Primeiro ponha os ovos a cozer em água (aproximadamente 10 minutos). Passe por água fria para parar a cozedura e deixe arrefecer.\nEntretanto, escorra o grão, o atum e reserve.\nLave bem os tomates. Corte o tomate em cubos e pique a cebola grosseiramente.\nNuma saladeira, coloque a cebola roxa, o tomate, o grão, e o atum e misture-os bem. Prepare o molho misturando o azeite, o sumo das limas e mexa com a ajuda de um garfo para incorporar\ntudo e tempere com sal e pimenta.\nRegue a salada com o molho e misture bem tudo novamente.\nPor fim disponha os ovos fatiados e decore com folhas comestíveis. Sirva de imediato!', 'salada_atum.jpg', 'Salada', 'Salada nutritiva e rápida, ótima para almoço leve.', 2, 'Económico'),
	(6, 'Tarte de Amêndoa', '1 h', '2 ovos\n30 g de xarope de agave\n100 g de iogurte grego natural\n100 g de farinha de aveia integral\n1 c. chá de fermento\n130 g de mel\n60 g de manteiga de amendoim com coco\n50 ml de bebida vegetal de arroz\n120 g de amêndoa palitada', 'Bata os ovos com uma batedeira eléctrica até ficarem com uma cor clara (demora 1 a 2 minutos). Junte o iogurte e posteriormente o xarope de agave e misture bem com uma espátula.\nAdicione a farinha de aveia e o fermento e envolva bem até obter uma massa cremosa.\nVerta para uma forma antiaderente de silicone pequena e leve ao forno pré-aquecido a 180ºC durante 15 minutos (ou até estar cozida e dourada por cima).\nRetire a base do forno e aumente a temperatura para 220ºC.\nPara a cobertura de amêndoa, coloque o mel num tacho pequeno e levo-o a lume médio. Deixe fervilhar ligeiramente durante 2 minutos.\nRetire o tacho do fogão e adicione a manteiga de amendoim e coco, mexendo sempre muito bem.\nColoque de novo ao lume durante mais 2 minutos. Retire, adicione a bebida vegetal de arroz e mexa muito bem.\nJunte as amêndoas palitadas, mexa até que a mistura fique homogénea e cubra a base com esta mistura. Leve novamente a tarte de amêndoa ao forno a 220ºC até tostar (cerca de 10 minutos).', 'tarte_amendoa.jpg', 'Sobremesas', 'Tarte amanteigada com recheio úmido de amêndoa.', 8, 'Médio'),
	(7, 'Pudim Flan', '1 h 30 min (inclui repouso)', '500 ml bebida vegetal de aveia\n1 casca de limão\n4 ovos\n150 g açúcar branco\n1 c. chá farinha\ncaramelo líquido q.b.\nhortelã q.b.', 'Para preparar o pudim flan, ferva a bebida vegetal de aveia com uma casca de limão. Deixe arrefecer até ficar morno.\nNuma taça à parte, misture o açúcar com a farinha. Junte os ovos batidos à farinha e açúcar, misture e depois junte a bebida vegetal de aveia em fio.\nUnte as forminhas com caramelo líquido tendo do cuidado de espalhar uniformemente pela forma.\nVerta a massa do pudim leve ao forno em banho-maria a 180ºC durante 30 minutos. Retire as formas do forno e deixe arrefecer por completo.\nPara desenformar, molhe a parte inferior da forma em água a ferver, coloque um prato por cima vire rapidamente e desenforme o pudim flan. Decore com hortelã a gosto.', 'pudim_flan.jpg', 'Sobremesas', 'Pudim cremoso com cobertura de caramelo.', 6, 'Económico'),
	(8, 'Bolo de Chocolate Húmido', '50 min', '200 g de chocolate\n150 g de manteiga\n6 ovos\n185 g de açúcar de coco\n1 c. chá de extrato de baunilha\nSal q.b.\n50 g de farinha de trigo peneirada\nAçúcar em pó q.b.', 'Comece por picar o chocolate. Coloque numa taça e junte a manteiga. Leve a derreter em banho-maria e reserve.\nSepare a clara da gema dos 6 ovos e reserve as claras.\nNuma taça larga coloque as gemas e adicione o açúcar de coco. Bata bem até obter uma mistura espumosa.\nJunte o chocolate derretido e envolva bem.\nAdicione o extrato de baunilha, o sal e a farinha de trigo peneirada. Envolva delicadamente. Reserve.\nBata as claras em castelo e envolva no preparado anterior com cuidado.\nUnte uma forma redonda de fundo amovível com óleo alimentar em spray (ou manteiga) e disponha uma folha de papel vegetal. Verta a massa do bolo de chocolate, alise a superfície e leve o bolo de chocolate ao forno a 200ºC por 15 a 20 minutos.\nDeixe arrefecer o bolo de chocolate antes de desenformar. Decore com açúcar em pó.', 'bolo_chocolate.jpg', 'Sobremesas', 'Bolo de chocolate húmido e fácil de preparar.', 8, 'Económico'),
	(9, 'Pastéis de Nata', '1 h 10 min', '1 embalagem de massa folhada fresca\n25 g de farinha de trigo peneirada\n1 c. de sopa de amido de milho peneirado\n175 g de açúcar\n250 ml de leite\n125 ml de água\nCasca de 1 limão\n1 pau de canela\n5 gemas de ovos', 'Pré-aquecer o forno a 250ºC.\nEsticar a massa folhada numa superfície enfarinhada com o rolo da massa de forma a ficar ligeiramente mais fina. Enrolar de forma bem apertada pela parte mais comprida do retângulo e cortar 30 segmentos iguais.\nColocar cada um dentro de uma forminhas e, com os dedos humedecidos, esticar a massa até sair ligeiramente do bordo de cada forma. Reservar.\nColocar num tachinho o leite, a água, o pau de canela, a casca de limão, o açúcar, a farinha e o amido de milho peneirados. Aquecer em lume baixo, mexendo sempre, até engrossar.\nJuntar uma concha do creme às gemas batidas, em fio, mexendo sempre. Colocar as gemas no tacho e misturar bem.\nRetirar a casca de limão e o pau de canela e deixar arrefecer. Verter o recheio nas formas até ? e levar de imediato ao forno durante 12 minutos.\nAssim que retirar as natas do forno, borrifar com um pouco de água fria. Servir mornas polvilhadas com canela em pó.', 'pastel_nata.jpg', 'Pastelaria', 'Versão caseira dos famosos pastéis de nata portugueses.', 12, 'Médio'),
	(10, 'Sopa de Abóbora com Gengibre', '45 min', '1 fio de azeite\n1 cebola laminada\nTomilho q.b.\n500 g abóbora manteiga em pedaços\nÁgua, q.b.\nGengibre ralado q.b.\nRaspa e sumo de 1 laranja\n1 c. café sal\nPimenta q.b.\nSementes de abóbora q.b.', 'Refogue a cebola num fio de azeite, num tacho médio, por cerca de 5 minutos. Adicione o tomilho e envolva bem.\nJunte a abóbora aos pedaços e cozinhe, mexendo sempre, por cerca de 4 minutos. Adicione a água, baixe o lume, tape e deixe cozer por cerca de 20 minutos.\nAbra a tampa e adicione o gengibre ralado, o sumo e a raspa da laranja e deixe cozinhar por mais 15 minutos. Tempere com sal e pimenta.\nTriture a sopa num copo de sumos e adicione água, se gostar de uma consistência mais líquida.\nSirva a sopa polvilhada com as sementes e o cebolinho picado.', 'sopa_abobora.jpg', 'Sopa', 'Sopa cremosa com toque picante de gengibre.', 4, 'Económico'),
	(11, 'Bruschetta de Tomate', '10 min', '2 c. de sopa de azeite\n1 c. de sopa de vinagre balsâmico\n125 g de queijo mozzarela\n250 g de tomate cereja em metades\nManjericão picado q.b\n3 fatias de pão alentejano tostadas\n3 dentes de alho', 'Coloque o azeite e o vinagre balsâmico num recipiente e envolva tudo muito bem. Corte o queijo e o tomate em metades e junte ao preparado anterior. Adicione o manjericão.\nLeve o pão ao grill do forno até ficar ligeiramente tostado de ambos os lados. Abra o alho em metade e esfregue nas tostas.\nColoque o preparado de queijo e tomate no topo de cada fatia e sirva com mais manjericão.', 'bruschetta_tomate.jpg', 'Entradas', 'Entrada italiana fresca e aromática.', 4, 'Económico'),
	(12, 'Ovos Rotos', '15 min', '5 batatas grandes\nSal q.b.\n1 c. chá de alho em pó\nAzeite q.b.\n1 cebola roxa picada\n50 g de presunto desfiado\n3 ovos\nCebolinho seco picado q.b.', 'Comece por cortar as batatas já lavadas em palitos. Disponha-as num tabuleiro forrado com papel vegetal e tempere com sal, alho em pó e um fio generoso de azeite. Envolva bem e leve ao forno a 180ºC por 15 a 20 minutos.\nNuma frigideira refogue a cebola roxa picada em azeite, adicione o presunto já desfiado e deixe cozinhar alguns minutos.\nDe seguida, junte os palitos de batata assada e envolva cuidadosamente. Faça três pequenos orifícios com a ajuda da colher de pau e parta os ovos nestes orifícios. Tape a frigideira e deixe cozinhar até que a clara fique branca.\nNo final, polvilhe o cebolinho seco picado e retire do lume. Sirva de imediato.', 'ovos_rotos.jpg', 'Entradas', 'Entrada espanhola rica e reconfortante.', 2, 'Médio'),
	(13, 'Sopa de Tomate Alentejana', '1 h 10 min', '3 tomates coração de boi\n4 batatas\n1 cebola média\n2 dentes de alho\n4 ovos classe S\n1 folha de louro\nÁgua q.b.\nAzeite q.b.\nSal q.b.\nCoentros picados q.b.\nFatias de pão q.b.', 'Lamine a cebola e os dentes de alho e reserve.\nCorte as batatas às rodelas e os tomates em cubos.\nNum tacho, coloque um fio de azeite e refogue a cebola e os alhos, juntamente com uma folha de louro até alourar.\nJunte o tomate em cubos, tempere com sal e deixe refogar por alguns minutos.\nAdicione de seguida as batatas e cubra tudo com água. Envolva bem e deixe cozer por 15 a 18 minutos.\nCom cuidado, parta 4 ovos para dentro do tacho, tape e deixe escalfar.\nRetire de lume e corte o pão em fatias. Disponha-as nas taças de servir e sirva a sopa por cima.\nDecore com coentros picados e sirva de imediato.', 'sopa_tomate.jpg', 'Sopa', 'Sopa aromática e levemente ácida.', 4, 'Económico'),
	(14, 'Massa à Carbonara', '30 min', '200 g de esparguete\n200 g de presunto\n100 g de parmesão ralado\n100 ml de água (da cozedura da massa)\n4 gemas de ovo\nAzeite q.b.\nSal q.b.\nPimenta q.b.\nSalsa picada q.b.', 'Numa taça, disponha as gemas de ovo e o parmesão ralado e misture bem com o auxílio de um garfo.\nTempere com sal e pimenta e reserve.\nCoza a massa de acordo com as instruções da embalagem.\nNuma tábua, disponha o pedaço de presunto e corte em pedaços.\nNuma frigideira, coloque um fio de azeite e frite os pedaços de presunto até ficarem crocantes. Desligue o lume e reserve.\nNa mesma frigideira, acrescente a massa já cozida, os ovos batidos e a cerca de 100 ml da água de cozedura da massa, misturando sempre até incorporar tudo.\nAcrescente o presunto crocante, finalize com salsa picada e sirva.', 'massa_carbonara.jpg', 'Massas', 'Clássica massa italiana cremosa.', 4, 'Médio'),
	(15, 'Sopa de Legumes', '40 min', '1 cebola laminada\n1 dente de alho\n½ alho francês laminado\n1 curgete em pedaços\n3 cenouras em pedaços\n½ cabeça de brócolos em pedaços\n1 c. café de sal\nAzeite q.b.', 'Começar por lavar e descascar todos os ingredientes.\nColocar num tacho a cebola, o alho, o alho francês, a curgete, a cenoura e o brócolos e cobrir tudo com água. Temperar com sal e regar com 1 colher de sopa de azeite. Deixar cozer por 30 minutos até os legumes estarem cozidos.\nAo fim deste tempo triturar com a varinha mágica até ficar cremoso.\nServir a sopa de legumes e decorar com um fio de azeite.', 'sopa_legumes.jpg', 'Sopa', 'Sopa caseira simples e nutritiva.', 4, 'Económico'),
	(16, 'Lasanha', '1 h 20 min', '1/2 cebola roxa\n3 dentes de alho\n1/2 pimento vermelho\n2 tomates\nAzeite q.b.\n450 g de carne picada\n5 c. sopa de molho de tomate\nManjericão picado q.b.\n100 ml de vinho branco\nSal q.b.\nPimenta q.b.\nMolho bechamel q.b.\nFolhas de lasanha q.b.\nQueijo mozzarella ralado q.b.\nQueijo mozzarella de búfala q.b.\nFolhas de manjericão q.b.', 'Comece por picar a cebola roxa e os dentes de alho, corte o pimento vermelho e o tomate em cubos. Reserve.\nNum tacho coloque um fio de azeite e frite a carne picada até ficar dourada. Quando chegar a este ponto, retire a carne e reserve.\nColoque no mesmo tacho um fio de azeite e refogue a cebola e os dentes de alho. Adicione o pimento e deixe cozinhar.\nFinalmente junte a carne picada, o tomate, o manjericão picado e o vinho branco e deixe cozinhar por alguns minutos até o álcool evaporar. Tempere com sal e pimenta.\nNum tabuleiro de forno, espalhe uma fina camada de molho bechamel, disponha algumas folhas de lasanha e verta metade do preparado de carne. Disponha novas folhas de lasanha e o resto da carne. Finalize com uma nova camada de folhas de lasanha e por cima uma camada de molho bechamel.\nPolvilhe queijo mozzarella ralado e desfaça o queijo mozzarella de bufala em pedaços. Leve a lasanha ao forno a 180ºC por 30 a 35 minutos até a lasanha ficar dourada.\nDecore a lasanha com folhas de manjericão e sirva de imediato.', 'lasanha.jpg', 'Massas', 'Clássica lasanha italiana gratinada.', 6, 'Médio'),
	(17, 'Bife à Marrame', '45 min', '2 c. sopa de azeite\n6 dentes de alho esmagados\n2 folhas de louro\n2 bifes de lombo\n1 c. café de sal\nPimenta q.b.\n50 g de manteiga sem sal\n200 g de natas culinárias\nBatata doce assada q.b.', 'Numa frigideira aquecer o azeite e juntar os alhos, o louro e os bifes de lombo. Temperar com sal e pimenta e deixar alourar de ambos os lados. Retirar e reservar.\nÀ mesma frigideira colocar a manteiga e deixar derreter.\nJuntar as natas, mexer e deixar engrossar.\nJuntar os bifes de lombo e regar com o molho.\nServir os bifes à marrare e acompanhar com batata doce assada.', 'bife.jpg', 'Carne', 'Prato tradicional português.', 1, 'Médio'),
	(18, 'Carne de Porco à Alentejana', '50 min', '800 g carne de porco\n800 g batatas\n400 g amêijoas frescas\n4 dentes de alho\n300 ml vinho branco\nAzeite, q.b.\n3 c. sopa massa de pimentão\nCoentros picados, q. b.\nSal q.b.\nPimenta q.b.', 'Comece por colocar as amêijoas em água com sal e deixe de molho durante 3h tendo em atenção para mudar a água de vez em quando.\nNuma taça coloque a carne, os alhos picados, sal, pimenta, vinho branco e a massa de pimentão. Deixe marinar por 1h.\nNum tabuleiro de ir ao forno, coloque uma folha de papel vegetal, disponha as batatas em cubos e deite um fio de azeite. Leve ao forno a 180ºC por 25 minutos, mexendo de vez em quando.\nNuma frigideira larga, coloque um fio de azeite e coloque a carne, sem a marinada, deixe a carne ganhar cor e só depois pode juntar a marinada.\nJunte as amêijoas à carne e tape a frigideira, por 4 minutos (até que as amêijoas estarem abertas). Junte então as batatas já assadas e envolva bem.\nPor fim é só juntar os coentros e sirva.', 'alentejana.jpg', 'Carne', 'Combinação clássica de porco e marisco.', 4, 'Médio'),
	(19, 'Hambúrguer Caseiro', '20 min', '400 g de carne do acém picada\n1 c. de chá de sal\nPimenta q.b.', 'Dividir a carne picada em 2 partes iguais\nMoldar em forma de bola e pressionar cada parte da carne para obter um formato de hambúrguer com cerca de 10 cm de diâmetro.\nTemperar a carne dos dois lados  com o sal e com a pimenta.\nGrelhar os hambúrgueres (nunca grelhar mais do que 2 de cada vez) numa frigideira anti-aderente bem quente, durante 1 minuto de cada lado, para obter um ponto médio da carne.\nServir no prato ou no pão com queijo, alface, tomate, cebola e pickle.', 'hamburguer.jpg', 'Carne', 'Hambúrguer simples e saboroso.', 2, 'Económico'),
	(20, 'Salmão Grelhado', '15 min', '1 lombo de salmão (300 g)\nSal q.b.\nPimenta q.b.\nSumo de limão q.b.\n250 g tomate cereja\nAzeite q.b.\nVinagre balsâmico q.b.\nManjericão q.b.', 'Comece por marinar o lombo de salmão temperando-o com sal e pimenta e regando-o com sumo de limão. Espalhe bem dos dois lados. Deixe marinar por 10 minutos.\nEntretanto prepare os tomates cereja cortando-os em metades. Coloque-os numa taça, tempere com sal e pimenta, 1 fio de azeite e vinagre balsâmica. Envolva bem e reserve.\nNuma frigideira anti aderente coloque o lombo de salmão com a pele virada para cima e deixe tostar. Vire-a e deixe tostar a pele até ficar crocante, mais ou menos 5 minutos. Retire do lume.\nNa mesma frigideira adicione as metades de tomate cereja e deixe saltear por alguns minutos na gordura do salmão.\nSirva os tomates cereja com folhas de manjericão e sirva juntamente com o salmão crocante.', 'lombo_salmão.jpg', 'Peixe', 'Peixe simples e saudável.', 2, 'Alto'),
	(21, 'Arroz de Polvo', '1 h', '2 kg polvo\n300 g arroz carolino\n1 cebola picada\n3 dentes de alho picados\n1 tomate maduro picado\n1 folha de louro\n1,5 l água de cozer o polvo\n100 ml vinho tinto\n60 ml azeite\nPimento vermelho q.b.\nPimentão Doce q.b.\nSal q.b.\nCoentros picados q.b.', 'Cozer o polvo até ficar macio e reservar a água.\nPara cozer o polvo, mergulhar o mesmo em água a ferver 3 vezes, este processo ajuda a que a pele se mantenha firme, se o polvo tiver congelado, colocar no tacho e deixar cozer lentamente, com cebola alho e um cálice de vinho tinto durante 1 hora (sem ferver)\nFazer um refogado com azeite, cebola, alho e tomate. Juntar o arroz, envolver e acrescentar a água da cozedura.\nCortar o polvo em pedaços e juntar ao arroz.\nCozinhar até o arroz ficar caldoso e finalizar com coentros.', 'arroz_polvo.jpg', 'Peixe', 'Prato português tradicional.', 4, 'Alto'),
	(23, 'Caril de Grão-de-Bico', '30 min', '400 g grão-de-bico cozido\n200 g abóbora manteiga\n400 ml leite de coco\n1 cebola\n3 dentes de alho\n1 c. chá caril em pó\n½ c. chá cominhos\n½ c. chá gengibre em pó\nSumo de 1/2 lima\nSal q.b.\nAzeite q.b.\nCoentros frescos q.b.\nArroz basmati para acompanhar', 'Numa frigideira alta ou um tacho largo, refogue a cebola em azeite e os dentes de alho durante cerca de 5 minutos.\nAcrescente as especiarias (caril, gengibre e cominhos) e mexa mais uns minutos. Adicione o sal.\nAdicione o leite de côco e a abóbora cortada em pedaços, tape e deixe cozinhar por 15-20 minutos em lume brando.\nAdicione o grão de bico cozido e o sumo de lima, envolva e deixe cozinhar mais 5 minutos em lume brando.\nSirva com coentros e acompanhe com um arroz basmati.', 'caril_grao.jpg', 'Vegetariano', 'Caril aromático e nutritivo.', 4, 'Económico'),
	(24, 'Legumes Assados no Forno', '40 min', '1 cebola roxa às rodelas\n2 curgetes às rodelas\n2 tomates chucha às rodelas\n2 batatas doces às rodelas\n1 pimento amarelo às rodelas\n10 folhas de manjericão\nMolho de tomate q.b.', 'Corte todos os legumes às rodelas e reserve. Pique as folhas de manjericão.\nDisponha molho de tomate num fundo de uma travessa, diponsha algumas folhas de manjericão picado e disponha as rodelas de legumes de forma alternada.\nLeve ao forno a 180ºC por 30 minutos.\nDecore com manjericão fresco.', 'legumes_assado.jpg', 'Vegetariano', 'Acompanhamento vegetariano saudável.', 4, 'Económico'),
	(25, 'Risoto de Cogumelos', '45 min', '1 l de caldo de legumes\n1 cebola roxa\n4 dentes de alho\n400 g de cogumelos frescos (shitake, portobello e castanho)\n200 g de arroz risotto\nAzeite q.b.\n150 g de parmesão ralado\nSal q.b.\nPimenta q.b.\nCebolinho picado q.b.', 'Comece por preparar o caldo de legumes. Lave e descasque os legumes e leve a cozer em água fervente com um punhado de sal.\nAqueça um fio de azeite numa frigideira e adicione o alho e os cogumelos. Frite bem. Reserve e mantenha num local quente.\nColoque um fio generoso de azeite num tacho e adicione a cebola roxa picada e o alho. Adicione o arroz. Humedeça com um pouco de vinho verde e deixe os grãos absorverem por completo.\nDespeje uma concha pequena de caldo de legumes na panela, deixe o arroz absorver o líquido e, em seguida, adicione mais um pouco de vinho verde. Aos poucos, vá alternando com o caldo restante e o vinho até que o arroz estiver cozido.\nRetire a panela do calor e adicione o parmesão ralado. Deixe descansar um minuto antes de misturar para o risotto de cogumelos ficar cremoso.\nAdicione os cogumelos em pedaços e misture bem. Coloque por cima alguns cogumelos. Decore o risotto de cogumelos com cebolinho picado.', 'risoto_cogumelos.jpg', 'Vegetariano', 'Risoto cremoso e elegante.', 4, 'Médio'),
	(26, 'Mousse de Chocolate', '2 h (com frio)', '100 g chocolate picado\n1 c. sopa manteiga\n5 ovos, gema e clara separadas\n100 g açúcar branco', 'Levar o chocolate picado juntamente com a manteiga a derreter no microondas. Reservar.\nBater as claras em castelo e reservar no frigorífico.\nJuntar o chocolate derretido e bater bem.\nEnvolver delicadamente as claras no preparado até que a mousse fiquei homogénea e cremosa.\nDividir por taças e levar ao frigorifico por algumas horas.\nServir a mousse de chocolate.', 'mousse_chocolate.jpg', 'Sobremesas', 'Clássica mousse cremosa.', 6, 'Médio'),
	(27, 'Gelado de Frutos Vermelhos', '3 h 30 min', '500 g de frutos vermelhos congelados\nRaspa e sumo de 1 limão\n397 g de leite condensado\n600 ml de natas\nPedaços pequenos de morango q.b.', 'Comece por colocar os frutos vermelhos congelados numa taça grande e adicione a raspa e o sumo de 1 limão. Com um esmagador, esmague bem a fruta.\nJunte o leite condensado e envolva bem até obter uma mistura homogénea.\nÀ parte bata as natas liquidas até obter picos firmes. Adicione o preparado anterior às natas batidas e envolva delicadamente.\nVerta este preparado para uma forma retangular e espalhe alguns pedaços de morangos por cima. Tape com película aderente e leve ao congelador por pelo menos 4 horas.\nSirva bolas de gelado e delicie-se!', 'gelado_frutos_vermelhos.jpg', 'Sobremesas', 'Sobremesa leve e fresca.', 8, 'Médio'),
	(28, 'Arroz Doce', '45 min', '750 ml de bebida vegetal de amêndoa\n400 g de leite condensado\n210 g de arroz basmati\n2 paus de canela\nCasca de limão q.b.\nAmêndoa palitada q.b.\nCanela em pó q.b.', 'Numa taça, adicione o leite condensado, a bebida vegetal de amêndoa e misture. Reserve.\nNuma panela, adicione o arroz, 750 ml bebida vegetal de amêndoa, os paus de canela, a casca de limão e deixe cozinhar em lume médio até quase secar.\nAntes de secar o líquido da panela, adicione a mistura de leite condensado. Mexa até o arroz ficar bem cremoso.\nNa hora de servir o arroz doce, decore com amêndoa palitada e polvilhe com canela em pó.', 'arroz_doce.jpg', 'Sobremesas', 'Sobremesa tradicional portuguesa.', 6, 'Económico'),
	(29, 'Cheesecake', '4 h (inclui frio)', '200 g de bolacha maria\n100 g de manteiga\n400 g de queijo creme\n400 ml de natas\n100 g de açúcar em pó\n4 folhas de gelatina\n1 c. de café de aroma de baunilha\n150 g de doce de frutos vermelhos 100% sem açúcares adicionados', 'Triturar finamente as bolachas, juntar a manteiga derretida e misturar bem.\nColocar numa forma de aro amovível com 16 cm, forrada com papel vegetal e espalhar em toda a superfície, pressionando bem. Levar ao frigorífico.\nBater o queijo creme com as natas até obter uma mistura fofa e leve.\nJuntar o açúcar e bater mais um pouco.\nDemolhar a gelatina em água fria, escorrer bem e aquecer um pouco em banho maria para derreter.\nIncorporar a gelatina no queijo creme, batendo mais um pouco.\nVerter o preparado por cima da camada de bolacha e levar ao frigorífico durante 2 horas.\nRetirar e espalhar por cima o doce de frutos vermelhos com cuidado para não se misturar com o creme.\nLevar novamente ao frigorífico por mais 6 horas para ficar bem firme.', 'cheesecake.jpg', 'Sobremesas', 'Cheesecake fresco e delicioso.', 10, 'Médio'),
	(30, 'Gelado de Chocolate', '3 h (inclui congelação)', '600 ml de natas frescas\n540 ml de leite condensado magro\n45 g de cacau magro em pó\n150 g de chocolate negro\n1 c. chá de extrato de baunilha', 'Numa taça misture o leite condensado, o cacau e o extrato de baunilha.\nÀ parte bata as natas até ficarem firmes.\nJunte as natas batidas à mistura anterior com muito cuidado com a ajuda de uma espátula.\nPique o chocolate negro em pedaços ou muito finamente e junte ao preparado do gelado guardando alguns pedaços para a decoração. Envolva cuidadosamente.\nDespeje o preparado numa forma rectangular, alise com as costas de uma colher ou uma espátula.\nPolvilhe o restante do chocolate picado, envolva em película aderente e leve ao congelador entre 2 a 6h dependendo da textura desejada.\n\n', 'gelado_chocolate.jpg', 'Sobremesas', 'Gelado cremoso sem máquina.', 6, 'Médio'),
	(31, 'Hambúrguer de Soja', '50 min', '1 1/2 cháv. de soja texturizada fina\n1 cháv. de água quente\n1 c. chá de azeite\n1/2 cebola picada\n1 dente de alho picado\n1 c. sopa de molho de soja\n1 c. café de sal\nPimenta q.b.\nOrégãos q.b.\nCominhos q.b.\n2 c. sopa de flocos de aveia\n1 c. sopa de farinha de linhaça hidratada (em 3 c.sopa de água)\nSalada para acompanhar', 'Hidratar a soja texturizada com a água por 15 minutos.\nNuma frigideira colocar o azeite, a cebola e os alhos e deixar refogar.\nJuntar a soja hidratada e escorrida, o molho de soja, temperar com sal e pimenta, orégãos, cominhos, mexer por 3 a 5 minutos.\nTransferir para uma taça e juntar os flocos de aveia e a farinha de linhaça hidratada. Se estiver com uma consistência ainda mole, juntar farinha de aveia até que seja possível moldar a massa.\nMoldar os hambúrgueres de soja e dispor num tabuleiro. Levar ao forno a 180ºC por 20 minutos.\nServir de imediato e acompanhar com uma salada.', 'hambúrguer_soja.jpg', 'Vegetariano', 'Opção leve e rápida.', 4, 'Económico'),
	(32, 'Tagliatelle com Cogumelos', '25 min', '1 dente de alho\n30 g de azeite\n200 g de mistura de cogumelos\n150 g de massa tagliatelle\n1 c. café de sal\nPimenta q.b.\nSalsa picada q.b.', 'Numa frigideira aqueça o azeite e adicione os cogumelos laminados e o alho. Deixe saltear por alguns minutos.\nQuando os cogumelos estiverem cozinhados, junte a massa previamente cozida e escorrida e tempere com sal, pimenta e salsa picada. Envolva bem e retire do lume.\nSirva e decore com salsa fresca.', 'tagliatelle_cogumelos.jpg', 'Massas', 'Massa cremosa e reconfortante.', 2, 'Económico'),
	(33, 'Pataniscas de Bacalhau', '30 min', '1 cebola pequena\n300 g de bacalhau desfiado\nSalsa q.b.\n3 ovos\n150 ml de cerveja\n1 chávena de farinha de trigo com fermento\n1 limão\nAzeite q.b.\nPimenta q.b.\n1 chávena de arroz\n3 dentes de alho\n3 dentes de cenouras\n2 1/2 chavena de água\nSal q.b.', 'Comece por fritar os dentes de alho fatiados num tacho com um fio de azeite. Após cerca de 1 minuto adicione a cenoura em pequenos pedaços e deixe cozinhar mais 1 minuto.\nApós este período adicione o arroz e deixe fritar ligeiramente. Acrescente a água, e o sal a gosto e deixe cozinhar cerca de 10 minutos.\nPara as pataniscas, comece por ralar a cebola e junte-a ao bacalhau desfiado. Adicione a este um molhe de salsa bem picada, as gemas dos ovos. Mexa bem e adicione a cerveja aos poucos para que as pataniscas não fiquem muito líquidas.\nAdicione a farinha de trigo, o sal, a pimenta e o sumo de 1 limão a gosto e volte a misturar.\nNuma taça bata as claras em castelo, assim que estiverem firmes adicione à restante massa.\nDisponha porções do preparado num tabuleiro forrado com papel vegetal. Leve ao forno pré-aquecido a 180ºC, durante 20 minutos, ou até dourar.\nAcompanhe com o arroz, regue as pataniscas com sumo de limão e guarneça com salsa.', 'pataniscas.jpg', 'Peixe', 'Petisco português tradicional.', 4, 'Médio'),
	(34, 'Bife de Frango Panado', '25 min', '4 bifes de frango\n1 c. café de sal\nPimenta q.b.\n1 c. de chá de alho em pó\n1 limão\n1 ovo classe L\n4 c. de sopa de pão ralado\n150 ml de óleo', 'Temperar os bifes com o sal, a pimenta, o alho em pó e o sumo de meio limão.\nColocar o ovo num prato fundo e bater.\nPassar os bifes pelo ovo batido e depois pelo pão ralado.\nFritar numa frigideira com o azeite bem quente, de ambos os lados, até ficarem dourados.\nRetirar para um prato com papel absorvente para retirar o excesso de gordura.\nRegar com o restante sumo de limão e servir.', 'bife_frango_panado.jpg', 'Carne', 'Clássico panado crocante.', 2, 'Económico'),
	(35, 'Brownie de Chocolate', '35 min', '4 ovos\n200 g de açúcar mascavado\n250 g de manteiga derretida\n175 g chocolate negro derretido\n150 g farinha de trigo\n2 c. chá fermento em pó\n100 g de pepitas de chocolate\nGelado q.b. (opcional)', 'Aqueça o forno a 160ºC. Unte bem uma forma retangular com um pouco de manteiga e cubra o fundo com papel vegetal.\nNuma taça, mexa bem os ovos com o açúcar, até obter uma consistência cremosa. Junte a manteiga derretida e o chocolate também derretido, e mexa.\nAdicione a farinha e o fermento previamente peneirados à mistura do chocolate e mexa bem o preparado.\nJunte metade das pepitas de chocolate e envolva bem.\nEspalhe no tabuleiro o preparado, polvilhe as restantes pepitas de chocolate e leve ao forno por 30-40 minutos.\nDeixe arrefecer à temperatura ambiente.\n        Dica: Antes de retirar do forno, verifique se o centro está cozido.\nRetire da forma e corte aos quadradinhos. Se desejar, sirva acompanhado do gelado de baunilha.', 'brownie.jpg', 'Sobremesas', 'Brownie húmido e intenso.', 12, 'Económico'),
	(36, 'Massa Fusilli', '50 min', '1 fio de azeite\n1 cebola picada\n2 dentes de alho picados\n1/2 curgete em cubos\n50 g tomate cherry em cubos\n120 g salmão em posta ao natural\n300 g de massa fusilli tricolor cozida\n50 g queijo parmesão ralado\nManjericão, q.b.', 'Numa frigideira refogar a cebola com o alho num fio de azeite.\nJuntar a curgete, o tomate cereja e deixar cozinhar.\nDe seguida juntar o salmão e massa fusilli previamente cozida e escorrida e o queijo parmesão ralado. Envolver bem.\nServir e decorar com manjericão.', 'massa_fusilli.jpg', 'Massas', 'Opção vibrante e saborosa.', 4, 'Económico'),
	(37, 'Bolo de cenoura', '50 min', '4 ovos  \r\n120 g de açúcar\r\n120 ml óleo vegetal\r\n300 g cenoura ralada\r\n150 g farinha\r\n1 c. de chá fermento em pó', 'Pré-aqueça o forno a 180 ºC.\r\nUnte uma forma com manteiga e farinha.\r\nNuma tigela bata as gemas, o açúcar, o óleo e a cenoura ralada.\r\nJunte a farinha e misture com um garfo.\r\nEnvolva as claras batidas em castelo.\r\nDeite o preparado e leve ao forno durante 30 minutos.\r\nRetire do forno e desenforme o bolo. Se quiser, prepare uma cobertura de chocolate - fica uma delícia.', 'bolo_cenoura.jpg', 'Sobremesas', 'É um bolo clássico e nunca falha. Simples, fofinho e húmido, este bolo de cenoura é tudo o precisa para adoçar o seu dia. Experimente esta receita fácil e deliciosa.', 15, 'Económico'),
	(38, 'Robalo no Forno', '50 min', '2 c. sopa de azeite\r\nCoentros, q.b.\r\nRodelas de limão, q.b.\r\n1 cebola laminada\r\n1 robalo limpo\r\n1 c. café sal\r\nPimenta, q.b.\r\n1 ramo de salsa fresca\r\nCoentros, q.b.\r\n2 c. sopa azeite\r\nVinho branco, q.b.\r\nBatatinhas assadas, q.b', 'Pré-aquece o forno a 250 ° C.\r\nCubra o fundo de uma assadeira grande com 2 colheres de sopa de azeite extra-virgem e os coentros, para o peixe não tocar no fundo da assadeira.\r\nEm cima das ervas, coloque as rodelas de limão e as fatias de cebola. Tempere o peixe com uma boa quantidade de sal e pimenta, tanto por dentro como por fora, e coloque sobre a cama de ervas e limão.\r\nRegue com 2 colheres de sopa de azeite e um pouco de vinho branco. Por fim, cubra a assadeira com papel de alumínio e coloque no forno durante 15-20 minutos.\r\nSirva com batatinhas assadas.', 'robalo_assado.jpg', 'Peixe', 'Este prato de robalo assado com ervas aromáticas e gengibre combina intensidade e delicadeza, saúde e cor, frescura e complexidade. Descubra como preparar.', 4, 'Económico'),
	(39, 'Frango Assado', '1h 20min', '1 frango inteiro\r\n250 ml vinho branco\r\n3 a 4 c.sopa azeite\r\n1 c. chá massa de pimentão\r\n4 dentes de alho\r\nSumo de 1 limão\r\nSal, q.b.\r\nPimenta, q.b.\r\n2 folhas de louro\r\nAlecrim, q.b.\r\n350 g batatas\r\nTomilho, q.b.', 'Comece por preparar a marinada: misture o vinho branco com o azeite, a massa de pimentão, os dentes de alho inteiros, o sumo de limão e misture bem.\r\nDisponha o frango inteiro num tabuleiro largo. Pique um limão com um garfo e coloque-o na cavidade do frango.\r\nCom fio de cozinha ate bem as pernas. Regue a marinada por cima do frango, espalhe bem com as mãos.\r\nTempere com sal e pimenta, parta 2 folhas de louro em pedaços e junte ainda alecrim a gosto. Leve ao forno a 190ºC por pelo menos 1 hora até o frango ficar bem douradinho.\r\nEntretanto, descasque as batatas. Corte em pedaços. Regue com azeite, tempere com sal e pimenta e leve ao forno, por 25 a 30 minutos mexendo regularmente.\r\nSirva o frango assado com limão juntamente com as batatas assadas no forno. Decore com rodelas de limão e mais alecrim.', 'frango_assado.jpg', 'Crane', 'Um clássico irresistível que nunca sai de moda: frango saboroso e batatas douradas, perfeito para uma refeição em família!', 6, 'Económico'),
	(40, 'Ovos Recheados', '25 min', '4 ovos\r\n2 fatias de presunto em tiras finas\r\n2 c. sopa de iogurte natural\r\n1 c. chá de mostarda dijon\r\n1 c. café de sal\r\nPimenta q.b.\r\nSalsa picada q.b.', 'Cozer os ovos em água, assim que começar a ferver deixar cozer por 15 minutos.\r\nRetirar do lume e mergulhar em água fria.\r\nDescascar os ovos e reservar.\r\nNuma frigideira fritar as tiras de presunto até ficar crocante e reservar.\r\nColocar as gemas numa taça, esmagar bem e juntar o iogurte, a mostarda, o sal e a pimenta e a salsa picada e envolver bem.\r\nColocar esta mistura no centro da clara cozida, polvilhar com o crocante de presunto e decorar com salsa picada.', 'ovos_recheado.jpg', 'Entradas', 'Os ovos recheados são uma entrada prática e saborosa, que transforma a simplicidade dos ovos cozidos num petisco irresistível e cheio de criatividade.', 4, 'Económico'),
	(116, 'Rolo de Carne com Massa Folhada', '45 min', '1 c. sopa de azeite<br />\r\n1 cebola picada<br />\r\n2 dentes de alho picados<br />\r\n400 g de carne picada<br />\r\nOrégãos q.b.<br />\r\nAlecrim seco q.b.<br />\r\n1 folha de louro<br />\r\n1 c. café de sal<br />\r\nPimenta q.b.<br />\r\n1 embalagem de massa folhada<br />\r\n100g de espinafres<br />\r\n1 ovo batido<br />\r\nSalada q.b.', 'Numa frigideira, refogue a cebola picada e os dentes de alho picados finamente num fio de azeite.<br />\r\nQuando a cebola estiver tenra, junte a carne, polvilhe com os orégãos e o alecrim, acrescente o louro e envolva bem.<br />\r\nTempere com sal e pimenta e cozinhe até a carne ficar bem dourada.<br />\r\nRetire o louro e deixe arrefecer.<br />\r\nEstenda a massa folhada e, a meio, disponha a carne picada sobre o comprido.<br />\r\nPor cima coloque os espinafres e enrole, cobrindo tudo com a massa e apertando bem dos lados, de modo a criar um rolo fechado.<br />\r\nPincele com o ovo batido e leve ao forno por cerca de 20 minutos ou até a massa estar bem cozinhada e dourada.<br />\r\nAcompanhe com uma salada.', 'e3fb15b6f293e1191a05dd50f908cd65.jpg', 'Carne', 'Uma versão prática e deliciosa do clássico bife Wellington: este rolo de carne picada, envolvido em massa folhada, é perfeito para impressionar sem complicações.', 4, 'Económico'),
	(117, 'a', '5', 'ss<br />\r\nsss<br />\r\nsssss', 'hjshbd<br />\r\nwljbnjwf<br />\r\nsbjbjhsw', '6966792e344f2.png', 'Entradas', 'gagdgh', 2, 'Económico');

-- A despejar estrutura para tabela therecipe.utilizadores
CREATE TABLE IF NOT EXISTS `utilizadores` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(200) DEFAULT NULL,
  `password` varchar(350) DEFAULT NULL,
  `email` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- A despejar dados para tabela therecipe.utilizadores: ~4 rows (aproximadamente)
INSERT INTO `utilizadores` (`id`, `nome`, `password`, `email`) VALUES
	(1, 'Eduarda', 'Eduarda1234', 'ana.eduarda.pinto71@gmail.com'),
	(5, 'Ana', 'Duda12345', 'ana.eduarda.pinto2005@gmail.com'),
	(6, 'Duda', 'Dudaduda123', 'ana.eduarda.71@gmail.com'),
	(7, 'Claudia', 'Claudia1234', 'claudia71@gmail.com');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
